### PR TITLE
misc: Remove glide and use dep

### PR DESCRIPTION
**Pull request by jinankjain**
Since glide is deprecated as a dependency manager for go project and dep is now officially supported so it would be a good idea to move to dep

### CODE REVIEW

**Comment by danderson** [comment]
Thanks for the PR! I have to admit I'm really not a fan of dep, so far in my life it's done nothing but add complications where none existed before when using glide. I really hope something better is eventually adopted. That said, netboot's dependency graph is simple enough, so it should be feature equivalent.

Travis build is broken, can you update it to use `dep` instead of glide to install dependencies?

**Comment by danderson** [comment]
Build passes, thanks for the change!

**Comment by jinankjain** [comment]
@danderson Was this commit reverted?

**Comment by danderson** [comment]
Damnit! Sorry, I mistakenly did a forced push and nuked the commit. Working on fixing...

**Comment by danderson** [comment]
Fixed, I repushed from the branch in your fork. Sorry about that. I added branch protection on github to avoid this mistake happening again.

**Pull request merged**
